#! /bin/sh

## get node root (we will install the virtual environment there)
envdir=".env"

progdir=`dirname $0`
rpprogdir=`readlink -f $progdir`
pkgroot=`readlink -f $rpprogdir/../..`

envpath="$pkgroot/$envdir"

requirementspath="$pkgroot/requirements.txt"
creating="creating"

echo "Creating virtual environment in :  $envpath"

## if virtual env is already there, confirm re-creation
if [ -d "$envpath" ]; then
    echo "$envpath already exists."
    printf "Do you want to re-create the virtual environment? (yes/no) : "
    read recreate
    while [ ! '(' "$recreate" = "yes" -o "$recreate" = "no" ')' ]; do
        printf "            (yes/no) : "
        read recreate
    done
    
    if [ "$recreate" = "yes" ]; then
        creating="re-creating"
        echo "Cleaning up current virtual environment..."
        rm -rf $envpath
    else
        echo "Leaving current virtual environment as is."
        exit
    fi
        
fi

## Create the virtual environment
if virtualenv $envpath; then
    echo "Virtual environment created in $envpath"
else
    echo "Error while $creating virtual environment, exiting."
    exit 1
fi

## Install the pip dependencies
if [ -f "$requirementspath" ]; then
   echo "Installing dependencies from $requirementspath"
   ##"$envpath/bin/pip" install -r "$requirementspath"
   for line in `cat "$requirementspath"`; do
       "$envpath/bin/pip" install "$line"
   done
else
    echo "Not installing dependencies since no requirements file was found in $pkgroot"
fi

##add path to our local packages
# fetch the virtual environment's python installation folder
# (really, just get the first one)
pythondir=`ls "$envpath/lib" | awk '/^python/' | head -n 1`
pythonpath="$envpath/lib/$pythondir"
sitepackages="$pythonpath/site-packages"
path_file="$sitepackages/venv_local_packages.pth"

libs_path="$pkgroot/lib"

echo "Python dir is in $pythonpath"
echo "Adding path to $libs_path in $site_packages"

echo "## This file was autogenerated by the npm virtual env setup script." >> "$path_file"
echo "$libs_path" >> "$path_file"


## Done!!
echo "Done $creating virtual environment."

echo "Remember to source $envdir/bin/activate to use the virtual environment."
echo "or to run it by calling $envdir/bin/python"
